### ISSUE TITLE
nox.session and nox.parameterize no longer play nice together

### ISSUE THREAD

**Issue by dhermes** [theacodes/nox#103]
With `2018.7.31.dev1`, the following "legacy" config

```python
import nox


@nox.session
@nox.parametrize("py", ["2.7", "3.7"])
def now(session, py):
    session.interpreter = "python{}".format(py)
    session.install("pytest")
    session.run("py.test")
```

fails with a hard-to-grok (I'm still source-diving) error:

```
$ nox -s "now(py='2.7')" -r
nox > Running session now(py='2.7')
nox > Session now(py='2.7') raised exception AttributeError("'function' object has no attribute 'python'")
Traceback (most recent call last):
  File ".../python3.7/site-packages/nox/sessions.py", line 283, in execute
    self._create_venv()
  File ".../python3.7/site-packages/nox/sessions.py", line 256, in _create_venv
    if self.func.python is False:
AttributeError: 'function' object has no attribute 'python'
nox > Session now(py='2.7') failed.
```

**Comment by dhermes** [comment]
I'm fairly certain you need one (or multiple) `functools.wraps` in `nox._parametrize`. (I'll probably find out where too.)
