### ISSUE TITLE
Include `setuptools` as an explicit project requirement due to `import pkg_resources`

### ISSUE THREAD

**Issue by jwilges** [theacodes/nox#271]
**Describe the bug**
`nox` depends on `setuptools` but does not specify it explicitly in `setup.py`. This may not be a common issue, but in a minimal CI environment, I ran into this issue.

**How to reproduce**
If `setuptools` is not present, `nox` cannot import `pkg_resources`.

See the abbreviated console session below for an example:

```
> nox --help
Traceback (most recent call last):
  File "...\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\AppData\Roaming\Python\Python38\Scripts\nox.exe\__main__.py", line 5, in <module>
  File "...\AppData\Roaming\Python\Python38\site-packages\nox\__main__.py", line 24, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
> pip install setuptools
Collecting setuptools
  ...
Successfully installed setuptools-44.0.0
> nox --help
usage: nox [-h] [--version] [-l] [-s [SESSIONS [SESSIONS ...]]] [-k KEYWORDS] [-v] [-r] [--no-reuse-existing-virtualenvs] [-f NOXFILE] [--envdir ENVDIR]
           [-x] [--no-stop-on-first-error] [--error-on-missing-interpreters] [--no-error-on-missing-interpreters] [--error-on-external-run]
           [--no-error-on-external-run] [--install-only] [--report REPORT] [--non-interactive] [--nocolor] [--forcecolor]
           ...

Nox is a Python automation toolkit.
```

**Expected behavior**
The `nox` package should pull `setuptools` as an explicit dependency in `setup.py`.

**Comment by theacodes** [comment]
Cool, thanks for reporting this. If you'd like, you can send us a PR and we'll be happy to merge it. :)

**Comment by dhermes** [comment]
FWIW, it's not considered "idiomatic" usage of `pip` / `setuptools` to require it. For example, using `pip-compile` from `pip-tools` (which is what powers `pipenv`)

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --generate-hashes --output-file=requirementstxt requirements.txt.in
#
grpcio-tools==1.23.0 \
    --hash=sha256:056f2a274edda4315e825ac2e3a9536f5415b43aa51669196860c8de6e76d847 \
    ...

# WARNING: The following packages were not pinned, but pip requires them to be
# pinned when the requirements file includes hashes. Consider using the --allow-unsafe flag.
# setuptools==41.2.0        # via protobuf
```

**Comment by jwilges** [comment]
> FWIW, it's not considered "idiomatic" usage of `pip` / `setuptools` to require it. For example, using `pip-compile` from `pip-tools` (which is what powers `pipenv`)

I see what you're getting at: if your base Python environment has `setuptools` provided by a system package for example, that's the correct way to fill the requirement. I saw it more as a direct dependency in this package's case (i.e. to be explicit) since `nox` directly uses the `pkg_resources` module, but it does look like it's a natural expectation that the base environment should have it. I'll close this as this seems to be expected/accepted behavior.

**Comment by jaraco** [comment]
I disagree with the assessment here. I've been working to remove implicit dependencies on setuptools/pkg_resources across the ecosystem. To that end, I've removed setuptools from my system site-packages, and it causes tools like nox to fail. Here's how it failed for me:

```
pipx bugfix/importlib-metadata $ pip-run --use-pep517 'git+https://github.com/cs01/nox.git@5ea70723e9e6#egg=nox' -- -m nox --session lint                                 
  Running command git clone -q https://github.com/cs01/nox.git /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-install-owx2bfiv/nox
Collecting nox
  Cloning https://github.com/cs01/nox.git (to revision 5ea70723e9e6) to /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-install-owx2bfiv/nox
  WARNING: Did not find branch or tag '5ea70723e9e6', assuming revision or ref.
  Running command git checkout -q 5ea70723e9e6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting argcomplete<2.0,>=1.9.4
  Using cached argcomplete-1.11.1-py2.py3-none-any.whl (36 kB)
Collecting colorlog<4.0.0,>=2.6.1
  Using cached colorlog-3.2.0-py2.py3-none-any.whl (17 kB)
Collecting py<2.0.0,>=1.4.0
  Using cached py-1.8.1-py2.py3-none-any.whl (83 kB)
Collecting virtualenv>=14.0.0
  Using cached virtualenv-16.7.9-py2.py3-none-any.whl (3.4 MB)
Building wheels for collected packages: nox
  Building wheel for nox (PEP 517) ... done
  Created wheel for nox: filename=nox-2019.5.30-py2.py3-none-any.whl size=37908 sha256=3c741e5863c94da34d1e02320a2c1e2db7c8a49d93e04fdca04a6a51140bbdec
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-63lfyuat/wheels/99/9d/a5/379c269087d523ca731d8606b0722dcbe3b70a96cb81363a91
Successfully built nox
Installing collected packages: argcomplete, colorlog, py, virtualenv, nox
Successfully installed argcomplete-1.11.1 colorlog-3.2.0 nox-2019.5.30 py-1.8.1 virtualenv-16.7.9
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-run-p0nsfi0r/nox/__main__.py", line 24, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

If `setuptools` or `pkg_resources` is imported by the library, some version of setuptools should be declared as a dependency.

However, since pkg_resources is deprecated in favor of importlib.resources and importlib.metadata, I'd suggest just moving to those implementations for nox.
