### ISSUE TITLE
Having a space in the username keeps Nox from finding needed files

### ISSUE THREAD

**Issue by pscosta5** [theacodes/nox#284]
**Describe the bug**
Any installation command results in a `FileNotFoundError` when using Nox in Windows Subsystem for Linux if there is a space in the username.

**How to reproduce**

```python
import nox

@nox.session
def tests(session):
    session.install('pytest')

```

Calling

```zsh
➜  nox --version
2019.11.9
➜ nox
nox > Running session tests
nox > Creating virtual environment (virtualenv) using python in .nox/tests
nox > pip install pytest
nox > Session tests raised exception FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/pcosta/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox/sessions.py", line 406, in execute
    self.func(session)
  File "/mnt/c/Users/Paulo Costa/linux/test/noxfile.py", line 5, in tests
    session.install('pytest')
  File "/home/pcosta/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox/sessions.py", line 306, in install
    self._run("pip", "install", *args, external="error", **kwargs)
  File "/home/pcosta/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox/sessions.py", line 222, in _run
    return nox.command.run(args, env=env, path=self.bin, **kwargs)
  File "/home/pcosta/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox/command.py", line 108, in run
    return_code, output = popen(
  File "/home/pcosta/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox/popen.py", line 28, in popen
    proc = subprocess.Popen(args, env=env, stdout=stdout, stderr=stderr)
  File "/home/pcosta/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/pcosta/.pyenv/versions/3.8.1/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Paulo Costa/linux/test/.nox/tests/bin/pip'
```

**Expected behavior**

Seems that the process does not properly account for the space in the user name. Path _should_ be `/mnt/c/Users/Paulo\ Costa/linux/test/.nox/tests/bin/pip`.

---

Thanks a lot!

**Comment by theacodes** [comment]
Aw. This should be relatively simple to fix, I hope. If you wanna give a go at sending a pull request for it that would be rad!

**Comment by pscosta5** [comment]
I'll give it a shot at it sometime next week!

**Comment by theacodes** [comment]
Rad! Let us know if you need any help!

**Comment by pscosta5** [comment]
I just wanted to update that I'm still working on this!

The main issue is that `subprocess.Popen` really does not like spaces!

```python
import subprocess

path = ...
command = path + ["install"]
subprocess.Popen(command)
```

This fails if path is set to any of the below attempts
- `"/mnt/c/Users/Paulo Costa/..."`
- `"'/mnt/c/Users/Paulo Costa/...'"`
- `'"/mnt/c/Users/Paulo Costa/..."'`
- `"/mnt/c/Users/Paulo\ Costa/..."`
- `r"/mnt/c/Users/Paulo\ Costa/..."`

I'll keep working at it to see if we can format it in a way that `Popen` will accept!

**Comment by pscosta5** [comment]
_Edit: Removed my previous comment_

I just wanted to say that I'm still working on this!

Apparently the issue is not with the space, `subprocess.Popen` is having a hard time finding `pip` specifically.

```zsh
➜ pwd
/mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin

➜  ls | grep pip
pip
pip-3.8
pip3

➜  touch test
➜ python
>>> import subprocess
>>> subprocess.Popen(["/mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin/test"])
...
OSError: [Errno 8] Exec format error: '/mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin/test'
>>> subprocess.Popen(["/mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin/pip"])
...
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin/pip'
```

**Comment by theacodes** [comment]
Weird. This ccan happen on some systems with execv limits.

**Comment by pscosta5** [comment]
Yeah this doesn't even work on my shell

With `test.sh` as

```sh
echo "Hey!"

```

```zsh
➜  /mnt/c/Users/Paulo\ Costa/linux/pipx/.nox/tests-3-8/bin/test.sh
Hey!

➜ /mnt/c/Users/Paulo\ Costa/linux/pipx/.nox/tests-3-8/bin/pip
zsh: /mnt/c/Users/Paulo Costa/linux/pipx/.nox/tests-3-8/bin/pip: bad interpreter: /mnt/c/Users/Paulo: no such file or directory
```

Must be _something_ silly going on here.

**Comment by pscosta5** [comment]
Simply reinstalling nox via pipx seemed to have solved this 🙃. Going to close this issue.

**Comment by matteosantama** [comment]
Using pipx solved the problem for us too!
