### ISSUE TITLE
nox invocation of `poetry install` fails with TypeError (passing None)

### ISSUE THREAD

**Issue by ToddG** [theacodes/nox#285]
**Describe the bug**
I'm following this tutorial:
https://cjolowicz.github.io/posts/hypermodern-python-01-setup/

Running `nox` or `nox -r` fails due to an error in poetry. It seems that nox is invoking poetry differently from the command line (which successfully runs `poetry install`).

noxfile
```python
    session.run("poetry", "install", "-v", external=True)
```
error
```bash
[TypeError]
expected string or bytes-like object
```

I've detailed this bug in greater detail here:
https://github.com/cjolowicz/hypermodern-python/issues/18

And added to a SO thread here:
https://stackoverflow.com/questions/59768651/how-to-use-nox-with-poetry/60190989#60190989

**How to reproduce**
```bash
git clone https://github.com/cjolowicz/hypermodern-python.git
cd hypermodern-python.git
git co -b remotes/origin/chapter07
nox
```

**Expected behavior**
Should have installed the local project, 'hypermodern-python',  and then proceeded to run the test suite.

**Comment by cjolowicz** [comment]
This is https://github.com/pypa/virtualenv/issues/1589 which was resolved in virtualenv 20.0.3.

**Comment by ToddG** [comment]
**REPRO**
```bash
# re-installed pyenv
rm -rf ~/.pyenv
curl https://pyenv.run | bash

# re-instaled python 3.8.1
pyenv install 3.8.1

# made this the default python
pyenv local 3.8.1

# verified that this repo/branch `chapter07` works with poetry
poetry install
poetry run python
# able to import hypermodern_python

# ran tests via poetry
poetry run pytest

# upgrade nox
pip install --user --upgrade nox
Requirement already up-to-date: nox in /Users/tdgreenw/.local/lib/python3.8/site-packages (2019.11.9)
Collecting virtualenv>=14.0.0 (from nox)
  Using cached https://files.pythonhosted.org/packages/18/cb/9799b00a192391cab56f1e6400bfdeb331afff7527e18dc3df25543782ff/virtualenv-20.0.3-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: colorlog<5.0.0,>=2.6.1 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (4.1.0)
Requirement already satisfied, skipping upgrade: py<2.0.0,>=1.4.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (1.8.1)
Requirement already satisfied, skipping upgrade: argcomplete<2.0,>=1.9.4 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (1.11.1)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (3.0.12)
Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (1.4.3)
Requirement already satisfied, skipping upgrade: six<2,>=1.12.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (1.14.0)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (0.3.0)
Installing collected packages: virtualenv
Successfully installed virtualenv-20.0.3

nox
# nox (fails with same TypeError)

# upgrade virtualenv
pip install -U virtualenv
 pip install -U virtualenv
Requirement already up-to-date: virtualenv in /Users/tdgreenw/.local/lib/python3.8/site-packages (20.0.3)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv) (1.4.3)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv) (0.3.0)
Requirement already satisfied, skipping upgrade: six<2,>=1.12.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv) (1.14.0)
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

nox
# nox (fails with same TypeError)
```

**ERROR**
```bash
nox > poetry install -v
canonicalize_name: hypermodern-python
cname: hypermodern-python
canonicalize_name: click
cname: click
canonicalize_name: sphinx
cname: sphinx
canonicalize_name: sphinx-rtd-theme
cname: sphinx-rtd-theme
canonicalize_name: sphinx-autodoc-typehints
cname: sphinx-autodoc-typehints
canonicalize_name: pytest
cname: pytest
canonicalize_name: coverage
cname: coverage
canonicalize_name: pytest-cov
cname: pytest-cov
canonicalize_name: pytest-mock
cname: pytest-mock
canonicalize_name: xdoctest
cname: xdoctest
canonicalize_name: sphinx
cname: sphinx
canonicalize_name: sphinx-rtd-theme
cname: sphinx-rtd-theme
canonicalize_name: sphinx-autodoc-typehints
cname: sphinx-autodoc-typehints
Using virtualenv: /Users/tdgreenw/repos/ext/hypermodern-python/.nox/tests-3-8
canonicalize_name: pip
cname: pip
canonicalize_name: None

[TypeError]
expected string or bytes-like object

Traceback (most recent call last):
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/tdgreenw/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/tdgreenw/.poetry/lib/poetry/console/commands/install.py", line 47, in handle
    installer = Installer(
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/Users/tdgreenw/.poetry/lib/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/Users/tdgreenw/.poetry/lib/poetry/repositories/installed_repository.py", line 26, in load
    package = Package(name, version, version)
  File "/Users/tdgreenw/.poetry/lib/poetry/packages/package.py", line 42, in __init__
    self._name = canonicalize_name(name)
  File "/Users/tdgreenw/.poetry/lib/poetry/utils/helpers.py", line 27, in canonicalize_name
    cname =  _canonicalize_regex.sub("-", name).lower()
```

**Comment by ToddG** [comment]
BTW - Where is the PR/commit for updating/pinning the virtualenv dependency to >= 20? 

I ask b/c In the repro below, I delete both pyenv and poetry and start from scratch... and the old virtualenv is being installed. So either the instructions on your blog need to be updated and/or the dependency on virtualenv needs to be updated here in nox.

```bash
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:35 $ rm -rf ~/.poetry
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:35 $ rm -rf ~/.pyenv
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:36 $ pwd
/Users/tdgreenw/repos/ext/hypermodern-python
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:36 $ cd
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~
09:36 $ ls ~/.python_history
/Users/tdgreenw/.python_history
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~
09:36 $ git st
fatal: not a git repository (or any of the parent directories): .git
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✘-128 ~
09:36 $ cd repos/
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos
09:36 $ cd ext/
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext
09:36 $ git st
fatal: not a git repository (or any of the parent directories): .git
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✘-128 ~/repos/ext
09:36 $ cd hypermodern-python/
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:36 $ h
total 168
 0 drwxr-xr-x  26 tdgreenw  staff    832 Feb 12 09:24 .
 0 drwxr-xr-x   3 tdgreenw  staff     96 Feb  6 13:57 ..
 8 -rw-r--r--   1 tdgreenw  staff     28 Feb 12 06:24 .darglint
 8 -rw-r--r--   1 tdgreenw  staff    116 Feb 12 06:24 .dockerignore
 8 -rw-r--r--   1 tdgreenw  staff    256 Feb 12 06:24 .flake8
 0 drwxr-xr-x  13 tdgreenw  staff    416 Feb 12 09:13 .git
 0 drwxr-xr-x   3 tdgreenw  staff     96 Feb 12 06:24 .github
 8 -rw-r--r--   1 tdgreenw  staff    103 Feb 12 06:24 .gitignore
 0 drwxr-xr-x   4 tdgreenw  staff    128 Feb 12 06:26 .mypy_cache
 0 drwxr-xr-x   9 tdgreenw  staff    288 Feb 12 09:28 .nox
 0 drwxr-xr-x   6 tdgreenw  staff    192 Feb 12 09:24 .pytest_cache
 8 -rw-r--r--   1 tdgreenw  staff      6 Feb 12 09:20 .python-version
 0 drwxr-xr-x   7 tdgreenw  staff    224 Feb 12 06:26 .pytype
 8 -rw-r--r--   1 tdgreenw  staff    170 Feb 12 06:24 .readthedocs.yml
 8 -rw-r--r--   1 tdgreenw  staff    587 Feb 12 06:24 Dockerfile
 8 -rw-r--r--   1 tdgreenw  staff   1072 Feb  6 13:58 LICENSE
 8 -rw-r--r--   1 tdgreenw  staff    707 Feb 12 06:24 README.md
 0 drwxr-xr-x   3 tdgreenw  staff     96 Feb 12 06:36 __pycache__
 0 drwxr-xr-x   6 tdgreenw  staff    192 Feb 12 06:24 docs
 8 -rw-r--r--   1 tdgreenw  staff     70 Feb 12 06:24 mypy.ini
 8 -rw-r--r--   1 tdgreenw  staff   1933 Feb 12 06:36 noxfile.py
64 -rw-r--r--   1 tdgreenw  staff  31492 Feb 12 06:24 poetry.lock
 8 -rw-r--r--   1 tdgreenw  staff   1225 Feb 12 06:24 pyproject.toml
 8 -rw-r--r--   1 tdgreenw  staff     32 Feb 12 06:24 pytype.cfg
 0 drwxr-xr-x   4 tdgreenw  staff    128 Feb  6 14:00 src
 0 drwxr-xr-x   7 tdgreenw  staff    224 Feb 12 09:24 tests
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:36 $ git st
On branch remotes/origin/chapter07
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   noxfile.py

no changes added to commit (use "git add" and/or "git commit -a")
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✚ 1]
09:36 $ git co .
Updated 1 path from the index
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:36 $ git st
On branch remotes/origin/chapter07
nothing to commit, working tree clean
-bash: /Users/tdgreenw/.pyenv/bin/pyenv: No such file or directory
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:36 $ curl https://pyenv.run | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   285  100   285    0     0    698      0 --:--:-- --:--:-- --:--:--   700
Cloning into '/Users/tdgreenw/.pyenv'...
remote: Enumerating objects: 667, done.
remote: Counting objects: 100% (667/667), done.
remote: Compressing objects: 100% (499/499), done.
remote: Total 667 (delta 333), reused 260 (delta 77), pack-reused 0
Receiving objects: 100% (667/667), 379.67 KiB | 11.86 MiB/s, done.
Resolving deltas: 100% (333/333), done.
Cloning into '/Users/tdgreenw/.pyenv/plugins/pyenv-doctor'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 1), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), 38.62 KiB | 3.51 MiB/s, done.
Cloning into '/Users/tdgreenw/.pyenv/plugins/pyenv-installer'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 1), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), 5.99 KiB | 511.00 KiB/s, done.
Cloning into '/Users/tdgreenw/.pyenv/plugins/pyenv-update'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), 2.66 KiB | 340.00 KiB/s, done.
Cloning into '/Users/tdgreenw/.pyenv/plugins/pyenv-virtualenv'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 57 (delta 11), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (57/57), 34.86 KiB | 793.00 KiB/s, done.
Cloning into '/Users/tdgreenw/.pyenv/plugins/pyenv-which-ext'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), 2.92 KiB | 373.00 KiB/s, done.
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:37 $ source ~./bashrc
-bash: ~./bashrc: No such file or directory
✘-1 ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:37 $ source ~/.bashrc
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:37 $ pyenv install 3.8.1
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.1.tar.xz...
-> https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tar.xz
Installing Python-3.8.1...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.8.1 to /Users/tdgreenw/.pyenv/versions/3.8.1

✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:39 $ pyenv local 3.8.1
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:40 $ which python
/Users/tdgreenw/.pyenv/shims/python
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:40 $ python --version
Python 3.8.1
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:40 $ pip install pip -U
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.0.2
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:40 $ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.0.3
  - Downloading poetry-1.0.3-darwin.tar.gz (10.58MB)

Poetry (1.0.3) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:41 $ poetry --version
Poetry version 1.0.3
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
09:41 $ pip install --user --upgrade nox
Requirement already up-to-date: nox in /Users/tdgreenw/.local/lib/python3.8/site-packages (2019.11.9)
Requirement already satisfied, skipping upgrade: argcomplete<2.0,>=1.9.4 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (1.11.1)
Requirement already satisfied, skipping upgrade: py<2.0.0,>=1.4.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (1.8.1)
Requirement already satisfied, skipping upgrade: virtualenv>=14.0.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (20.0.3)
Requirement already satisfied, skipping upgrade: colorlog<5.0.0,>=2.6.1 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from nox) (4.1.0)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (3.0.12)
Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (1.4.3)
Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (0.3.0)
Requirement already satisfied, skipping upgrade: six<2,>=1.12.0 in /Users/tdgreenw/.local/lib/python3.8/site-packages (from virtualenv>=14.0.0->nox) (1.14.0)
✔ ~/repos/ext/hypermodern-python [remotes/origin/chapter07 L|✔]
```

Ok, so now let's follow the instructions and upgrade virtualenv...

```bash
pip install -U virtualenv
```

```bash
nox
```

**ERROR**
```bash
nox > poetry install

[TypeError]
expected string or bytes-like object
```

**Comment by cjolowicz** [comment]
Hi @ToddG , thanks for taking the time to report this! I think this is not a Nox issue.

Please try deleting virtualenv's app data as described [here](https://github.com/pypa/virtualenv/issues/1589#issuecomment-585389894).

Let's continue the discussion on the issue in the virtualenv project: https://github.com/pypa/virtualenv/issues/1589

**Comment by ToddG** [comment]
Thx, verified that nox can invoke `poetry install` successfully after removing virtualenv dir as described.
