### ISSUE TITLE
Handling stale caches

### ISSUE THREAD

**Issue by jackton1** [theacodes/nox#338]
**Describe the bug**
There's seems to be an issue with handling stale caches especially when used with GitHub actions.

```shell script
pip install psycopg2>=2.5.4
86 Session tests-3.6(database='postgres', django='2.2.10') raised exception FileNotFoundError(2, "No such file or directory: '/home/runner/work/django-check-constraint/django-check-constraint/.nox/tests-3-6-database-postgres-django-2-2-10/bin/pip'")
87 Traceback (most recent call last):
88 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/sessions.py", line 406, in execute
89 self.func(session)
90 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/_parametrize.py", line 163, in call_wrapper
91 return func(*args, **kwargs)
92 File "/home/runner/work/django-check-constraint/django-check-constraint/noxfile.py", line 36, in tests
93 "CPPFLAGS": "-I/usr/local/opt/openssl@1.1/include",
94 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/sessions.py", line 306, in install
95 self._run("pip", "install", *args, external="error", **kwargs)
96 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/sessions.py", line 222, in _run
97 return nox.command.run(args, env=env, path=self.bin, **kwargs)
98 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/command.py", line 109, in run
99 [cmd_path] + list(args), silent=silent, env=env, **popen_kws
100 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/nox/popen.py", line 28, in popen
101 proc = subprocess.Popen(args, env=env, stdout=stdout, stderr=stderr)
102 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/subprocess.py", line 729, in __init__
103 restore_signals, start_new_session)
104 File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/subprocess.py", line 1364, in _execute_child
105 raise child_exception_type(errno_num, err_msg, err_filename)
106 FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/django-check-constraint/django-check-constraint/.nox/tests-3-6-database-postgres-django-2-2-10/bin/pip': '/home/runner/work/django-check-constraint/django-check-constraint/.nox/tests-3-6-database-postgres-django-2-2-10/bin/pip'
107 Session tests-3.6(database='postgres', django='2.2.10') failed.
```

**How to reproduce**

```yaml
- uses: actions/cache@v1
   id: nox-cache
   if: startsWith(runner.os, 'Linux')
   with:
     path: .nox
     key: ${{ runner.os }}-nox-${{ hashFiles('noxfile.py') }}
     restore-keys: |
        ${{ runner.os }}-nox-
```

Runs with 
```
$ nox -x -r
```

**Expected behaviour**

Executes without errors and identifies errors in cache and invalidates them.

**Comment by theacodes** [comment]
Nox doesn't have cache invalidation logic. If you re-use a virtualenv
(`-r`), no will not attempt to invalidate any aspects of it. If you run
`install` in a cached virtualenv, then pip handles updating things that
need to be updated in terms of packages.
