### ISSUE TITLE
No longer Py3.5 compatible

### ISSUE THREAD

**Issue by s0undt3ch** [theacodes/nox#348]
**Describe the bug**
Contrary to what `setup.py` states, nox is no longer Py3.5 compatible.

**How to reproduce**
Try running under Py3.5

**Expected behavior**
Either drop 3.5 support or fix it.

```
17:33:36      amazon-ebs:                   Traceback (most recent call last):
17:33:36      amazon-ebs:                     File "/usr/local/bin/nox", line 7, in <module>
17:33:36      amazon-ebs:                       from nox.__main__ import main
17:33:36      amazon-ebs:                     File "/usr/local/lib/python3.5/dist-packages/nox/__main__.py", line 24, in <module>
17:33:36      amazon-ebs:                       from nox import _options, tasks, workflow
17:33:36      amazon-ebs:                     File "/usr/local/lib/python3.5/dist-packages/nox/workflow.py", line 20, in <module>
17:33:36      amazon-ebs:                       workflow: Iterable[Callable[..., Any]], global_config: argparse.Namespace
17:33:36      amazon-ebs:                     File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
17:33:36      amazon-ebs:                       tvars = _type_vars(params)
17:33:36      amazon-ebs:                     File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
17:33:36      amazon-ebs:                       _get_type_vars(types, tvars)
17:33:36      amazon-ebs:                     File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
17:33:36      amazon-ebs:                       t._get_type_vars(tvars)
17:33:36      amazon-ebs:                     File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
17:33:36      amazon-ebs:                       _get_type_vars(self.__args__, tvars)
17:33:36      amazon-ebs:                     File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
17:33:36      amazon-ebs:                       for t in types:
17:33:36      amazon-ebs:                   TypeError: 'ellipsis' object is not iterable
```

**Comment by s0undt3ch** [comment]
So, it seems that it does not work with Python 3.5.2, which is the version of python that ships with ubuntu 16.04, which sadly, we have to test against...

**Comment by s0undt3ch** [comment]
There's nothing the nox project should do to fix this.
