### ISSUE TITLE
nox can't create virtualenv

### ISSUE THREAD

**Issue by rkube** [theacodes/nox#355]
Hi,
I've start to explore using nox for a project. I've got a simple configuration file:
```
import nox
locations = "src"

@nox.session()
def lint(session):
    """Syntax and docstring linting."""
    session.run("flake8", "--docstring-convention google")
```

and run nox like this:
```
$ nox -rs lint
```

Doing this, I'm getting a BlockingIOError:
```
(openmpi) rkube@cori02:~/repos/delta> nox -rs lint
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python3.9 in .nox/lint
nox > Command /global/homes/r/rkube/.conda/envs/openmpi/bin/python3.9 -m virtualenv /global/u2/r/rkube/repos/delta/.nox/lint failed with exit code 1:
RuntimeError: failed to build image setuptools, pip because:
Traceback (most recent call last):
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 58, in _install
    installer.install(creator.interpreter.version_info)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 42, in install
    self._sync(filename, into)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
    copy(src, dst)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 64, in copytree
    shutil.copy(src_f, dest_f)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 169, in _fastcopy_sendfile
    raise err
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
BlockingIOError: [Errno 11] Resource temporarily unavailable: '/global/u2/r/rkube/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/setuptools-50.3.2-py3-none-any/setuptools/gui-32.exe' -> '/global/u2/r/rkube/repos/delta/.nox/lint/lib/python3.9/site-packages/setuptools/./gui-32.exe'

Traceback (most recent call last):
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 58, in _install
    installer.install(creator.interpreter.version_info)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 42, in install
    self._sync(filename, into)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
    copy(src, dst)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/site-packages/virtualenv/util/path/_sync.py", line 64, in copytree
    shutil.copy(src_f, dest_f)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 169, in _fastcopy_sendfile
    raise err
  File "/global/homes/r/rkube/.conda/envs/openmpi/lib/python3.9/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
BlockingIOError: [Errno 11] Resource temporarily unavailable: '/global/u2/r/rkube/.local/share/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-20.2.4-py2.py3-none-any/pip/_vendor/distlib/w32.exe' -> '/global/u2/r/rkube/repos/delta/.nox/lint/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe'

nox > Session lint failed.
```

Does anyone know what is going on here?

**Comment by V1NAY8** [comment]
For each `nox` session you need to install flake8. add the following line
`session.install("flake8")`

- It was working fine for me in `virtualenv` and running the same above code. 

- If you are using `conda`, can you create a new conda environment and try the same again?

- Also you can try rolling back to python 3.8.6 and doing the above because it works. :)

**Comment by theacodes** [comment]
Yeah, that's my guess as well. I'm going to go ahead and close this but if it's something else I'm happy to re-open.
